### ISSUE TITLE
Release v0.10.0 [xx.06.2020]

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#117]
#### Roadmap

* [ ] Move project to the modern state (dependencies, code, practices).
  * [ ] Reimplement server
    * [ ] Multi Workspace Support
    * [ ] Abstract Server without VS Code Connection usage
    * [ ] Services
      * [ ] Logger
      * [ ] Storage
      * [ ] Document
      * [ ] Language Service (?)
      * [ ] Scanner
    * [ ] Providers
      * [ ] Completion
      * [ ] Definition
      * [ ] Hover
      * [ ] Signature Help
      * [ ] Workspace Symbol
* [ ] Move CI to Azure Pipelines.
