### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#29]
* [ ] Use @types, update dependencies and target plugin only for VS Code 1.8.0 and above
  * [ ] Code refactoring
    * [ ] Use classes for parser, providers and services
    * [ ] Simplify Completion and SignatureHelp provider
    * [ ] Scanner optimization (if it's possible)
    * [ ] Cache -> Storage
  * [ ] Remove autocomplete for Variables, Functions and Mixins inside current document (covered by VS Code, fix #19)
  * [ ] Fix problem with update cache from current document
  * [ ] Remove `preview` status
  * [ ] May be add support foe "Find All References to a Symbol" (#21)

**Comment by octref** [comment]
@mrmlnc Do you mind updating this with latest plans? I can help with development, but I'm interested to see what you think would be essential for 1.0.

**Comment by mrmlnc** [comment]
I will think about it today.

**Comment by mrmlnc** [comment]
@octref done.

**Comment by octref** [comment]
@mrmlnc IMO we should implement find references and rename. I think we already have enough information for doing this, and they would be incredibly useful.
