### ISSUE TITLE
Checklist for 0.3.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#3]
## Services

  * [x] Parser
  * [x] Scanner
  * [x] Cache

## Providers

  * [x] Completion
    * [x] Variables & Mixins for all scopes
    * [x] Functions for Properties
  * [x] Hover
  * [x] Signature Help
    * [x] Mixin arguments
    * [x] Function arguments

## Documentation

  * [x] Read
  * [x] Read before release

## Release

  * [x] Tests
  * [x] Manual testing
  * [x] Twitter
